Shift responsibility of updating and creating points to decoder
NubeIO/module-core-loraraw pull request #29
Opened 2024-06-30 11:26 UTC by maharjanaman

Changes:
- Moved `decoder` package files to `pkg` package to avoid import cycle as decoder now references `Module` instance
- Decoder function only returns an error (if any)
- Logic to update points is moved to decoder functions
- If the decoder doesn't find the point in the device while performing the update, it creates a point and then performs an update (shifting responsibility to auto-create points to the decoder)
- Remove the operation to create points automatically when a device is added

2024-06-30 17:10 UTC, RaiBnod requested changes

2024-06-30 17:10 UTC, RaiBnod commented on decoder/microedge.go
> +	_ = updateDevicePoint("pulse", float64(p), device)
Let's move all `updateDevicePoint` at last, so it will have more better readability.

2024-07-02 00:29 UTC, Shiny380 requested changes
@maharjanaman 
> Remove the operation to create points automatically when a device is added

We still need this functionality, so the function that used to return a struct for this now will need to return a list of point names to be auto added

2024-07-02 21:53 UTC, Shiny380 approved these changes

2024-07-02 22:41 UTC, merged