Account for CMAC difference in driver-lora
NubeIO/module-core-loraraw pull request #36
Opened 2024-07-24 19:35 UTC by maharjanaman

2024-07-25 17:22 UTC, maharjanaman commented
@Shiny380 I've tested the changes for MicroEdge and Droplet points but I couldn't test for Ziphydrotap and rubix properly. I tried payload for rubix from [this comment](https://github.com/NubeIO/module-core-loraraw/pull/27#issuecomment-2164316216) but gave me an invalid payload as I assume the payload didn't have cmac. Please do let me know if anything needs to be changed further.

Also, while testing for rubix, only rssi and snr points were added automatically when the device was added.

2024-07-25 22:43 UTC, Shiny380 commented
Thanks Aman :) I'll get Tan to do testing for Rubix device as he has access to those

2024-07-25 23:13 UTC, Shiny380 requested changes
@maharjanaman see requested changes :)

2024-07-25 23:13 UTC, Shiny380 commented on decoder/rubix.go
>  func CheckPayloadLengthRubix(data string) bool {
can you please move this function to the core code somewhere. call it `checkLoRaRAWPayloadLength`. This section is unrelated to the rubix-data-encoding and actually relates to the LoRaRAW protocol which is core to this module.

This function will simply return `true` now

2024-07-25 23:13 UTC, Shiny380 commented on decoder/rubix.go
>  	dataLength, _ := strconv.ParseInt(data[12:14], 16, 0)
replace this `dataLength` with
```
dataLength := getInnerPayloadLength(data)
```
as seen in below comment

2024-07-25 23:13 UTC, Shiny380 commented on pkg/app.go
> +		data = data[14 : dataLen-12]
change this to be
```
data = data[14 : getInnerPayloadLength(data)]
```
```
func getInnerPayloadLength(data string) int {
    dataLength, _ := strconv.ParseInt(data[12:14], 16, 0)
    return dataLength
}
```
This removes any padding that existed from the encryption

2024-07-25 23:13 UTC, Shiny380 commented on pkg/app.go
> +	if (dataLen/2)%16 == expectedMod {
```
if (dataLen/2)%16 == expectedMod {
    // if(checkLoRaRAWPayloadLength(data) != true
        // return some error
    // data = data[14 : getInnerPayloadLength(data)]
}
if !devDesc.CheckLength(data) {
...
```

2024-07-30 05:49 UTC, Shiny380 commented
@lmtan91 will do testing on the rubix decoder

2024-08-07 05:36 UTC, Shiny380 approved these changes

2024-08-07 05:37 UTC, merged