Add decryption in the module itself
NubeIO/module-core-loraraw pull request #45
Opened 2024-09-04 02:26 UTC by maharjanaman

2024-09-04 04:21 UTC, Shiny380 requested changes
@maharjanaman this is not actually applied anywhere...
you need to be applying it here: https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L108

2024-09-04 04:21 UTC, Shiny380 commented on schema/device.go
> +	Min   int    `json:"minLength" default:"32"`
@maharjanaman I believe these have to be `maximum` and `minimum`. please confirm

2024-09-05 03:42 UTC, maharjanaman commented on schema/device.go
> +	Min   int    `json:"minLength" default:"32"`
For JSON, with `minLength` it's working with the UI (RCE). Are you referring to `struct` property `Min`. Have left similar comment in another comment too.
In JSON, we have `minLength` for string type and `minimum` for number type.

2024-09-05 18:01 UTC, maharjanaman commented
> @maharjanaman this decryption is not actually applied anywhere...? you need to be applying it here: https://github.com/NubeIO/module-core-loraraw/blob/master/pkg/app.go#L108

I've added `decryptData` method and used it as shown in the attached screenshot. From the recent refactor regarding decryption in driver-lora, every type of data (unique & legacy) are being transmitted over loRa1 serial port as it is, I didn't do any checks before calling the decryption method. @Shiny380 Is this okay?

![image](https://github.com/user-attachments/assets/754cf00f-dc7d-4512-8f67-fbca4de7ffea)

2024-09-05 22:15 UTC, Shiny380 commented
@maharjanaman I made some changes. I wasn't sure what the best way was to account for legacy devices so I needed to play with the code to think. I didn't test any of my code but I think this is an ok way to check for legacy devices

2024-09-06 05:26 UTC, maharjanaman commented
@Shiny380 Here, https://github.com/NubeIO/module-core-loraraw/blob/948b4488cdd43079871914cb42f920093a198e72/pkg/app.go#L136 If the device is `nil`, do we need to proceed with decryption and decoding?

2024-09-06 06:42 UTC, Shiny380 commented
legacy devices are fully encrypted, including the address bytes at the start, so we won't find the device in the database _**without**_ first attempting to decrypt it as a legacy packet

2024-09-20 03:09 UTC, Shiny380 commented
Resolves #32

2024-09-25 00:29 UTC, Shiny380 approved these changes

2024-09-25 00:29 UTC, merged